ALTER TABLE gov_sync_log
    ADD COLUMN IF NOT EXISTS reference_no VARCHAR(32),
    ADD COLUMN IF NOT EXISTS payload      JSONB,
    ADD COLUMN IF NOT EXISTS last_error   TEXT,
    ADD COLUMN IF NOT EXISTS dead_letter  BOOLEAN NOT NULL DEFAULT FALSE;
