
-- Government integration table

-- service_requests

CREATE TABLE service_requests (
                                  id               UUID          NOT NULL DEFAULT gen_random_uuid(),
                                  requester_id     UUID          NOT NULL,
                                  facility_id      UUID          NOT NULL,
                                  geo_location_id  UUID          NOT NULL,

                                  reference_no     VARCHAR(32)   NOT NULL,

                                  service_type     VARCHAR(32)   NOT NULL,

                                  status           VARCHAR(24)   NOT NULL DEFAULT 'PENDING',
                                  irembo_ticket_id VARCHAR(64),

                                  payload          JSONB,
                                  rejection_reason TEXT,

                                  submitted_at     TIMESTAMP     NOT NULL DEFAULT now(),
                                  resolved_at      TIMESTAMP,

                                  resolved_by      UUID,

                                  CONSTRAINT pk_service_requests
                                      PRIMARY KEY (id),

                                  CONSTRAINT fk_service_requests_requester
                                      FOREIGN KEY (requester_id)
                                          REFERENCES users(id),

                                  CONSTRAINT fk_service_requests_facility
                                      FOREIGN KEY (facility_id)
                                          REFERENCES facilities(id),

                                  CONSTRAINT fk_service_requests_geo
                                      FOREIGN KEY (geo_location_id)
                                          REFERENCES geo_locations(id),

                                  CONSTRAINT uq_service_requests_reference_no
                                      UNIQUE (reference_no),

                                  CONSTRAINT uq_service_requests_irembo_ticket
                                      UNIQUE (irembo_ticket_id),

                                  CONSTRAINT chk_service_requests_type
                                      CHECK (service_type IN (
                                                              'BIRTH_CERT',
                                                              'VACCINATION_CARD',
                                                              'REFERRAL',
                                                              'HEALTH_SUMMARY',
                                                              'REPRINT'
                                          )),

                                  CONSTRAINT chk_service_requests_status
                                      CHECK (status IN (
                                                        'PENDING',
                                                        'UNDER_REVIEW',
                                                        'APPROVED',
                                                        'REJECTED',
                                                        'IREMBO_SUBMITTED',
                                                        'COMPLETED'
                                          ))
);

CREATE INDEX idx_service_requests_requester
    ON service_requests(requester_id);

CREATE INDEX idx_service_requests_facility
    ON service_requests(facility_id);

CREATE INDEX idx_service_requests_status
    ON service_requests(status);

CREATE INDEX idx_service_requests_type
    ON service_requests(service_type);

COMMENT ON COLUMN service_requests.reference_no
    IS 'Human-readable reference number in format SR-YYYY-NNNNN. Generated by application before insert. Example: SR-2026-00042';

COMMENT ON COLUMN service_requests.payload
    IS 'Service-specific form data as JSONB. Structure varies by service_type. Never contains PHI directly — references other records by ID.';


-- service_request_docs


CREATE TABLE service_request_docs (
                                      id            UUID         NOT NULL DEFAULT gen_random_uuid(),
                                      request_id    UUID         NOT NULL,

                                      document_type VARCHAR(32)  NOT NULL,

                                      file_path     VARCHAR(512) NOT NULL,

                                      file_hash     VARCHAR(64)  NOT NULL,

                                      uploaded_at   TIMESTAMP    NOT NULL DEFAULT now(),

                                      CONSTRAINT pk_service_request_docs
                                          PRIMARY KEY (id),

                                      CONSTRAINT fk_service_request_docs_request
                                          FOREIGN KEY (request_id)
                                              REFERENCES service_requests(id)
                                              ON DELETE CASCADE,

                                      CONSTRAINT chk_service_request_docs_type
                                          CHECK (document_type IN (
                                                                   'ID_COPY',
                                                                   'BIRTH_PROOF',
                                                                   'FACILITY_LETTER',
                                                                   'OTHER'
                                              ))
);

CREATE INDEX idx_service_request_docs_request
    ON service_request_docs(request_id);

COMMENT ON COLUMN service_request_docs.file_hash
    IS 'SHA-256 hash of the file contents at upload time. Recomputed on access to detect tampering.';

COMMENT ON COLUMN service_request_docs.file_path
    IS 'Relative path inside the secure file storage bucket. Never a public URL.';


-- gov_sync_log

CREATE TABLE gov_sync_log (
                              id               UUID         NOT NULL DEFAULT gen_random_uuid(),
                              facility_id      UUID,

                              target_system    VARCHAR(16)  NOT NULL,

                              sync_type        VARCHAR(32)  NOT NULL,

                              status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',

                              idempotency_key  VARCHAR(128) NOT NULL,
                              payload_hash     VARCHAR(64),
                              retry_count      INT          NOT NULL DEFAULT 0,
                              error_message    TEXT,

                              synced_at        TIMESTAMP,
                              next_retry_at    TIMESTAMP,

                              created_at       TIMESTAMP    NOT NULL DEFAULT now(),

                              CONSTRAINT pk_gov_sync_log
                                  PRIMARY KEY (id),

                              CONSTRAINT fk_gov_sync_log_facility
                                  FOREIGN KEY (facility_id)
                                      REFERENCES facilities(id),

                              CONSTRAINT uq_gov_sync_log_idempotency
                                  UNIQUE (idempotency_key),

                              CONSTRAINT chk_gov_sync_log_target
                                  CHECK (target_system IN (
                                                           'NIDA',
                                                           'HMIS',
                                                           'IREMBO',
                                                           'RURA'
                                      )),

                              CONSTRAINT chk_gov_sync_log_sync_type
                                  CHECK (sync_type IN (
                                                       'IDENTITY_VERIFY',
                                                       'REPORT_PUSH',
                                                       'TICKET_SUBMIT',
                                                       'SCHEDULE_PULL'
                                      )),

                              CONSTRAINT chk_gov_sync_log_status
                                  CHECK (status IN (
                                                    'PENDING',
                                                    'IN_FLIGHT',
                                                    'SUCCEEDED',
                                                    'FAILED',
                                                    'DEAD_LETTER'
                                      )),

                              CONSTRAINT chk_gov_sync_log_dead_letter
                                  CHECK (
                                      retry_count < 5
                                          OR status = 'DEAD_LETTER'
                                      )
);

CREATE INDEX idx_gov_sync_log_status
    ON gov_sync_log(status);

CREATE INDEX idx_gov_sync_log_next_retry
    ON gov_sync_log(next_retry_at)
    WHERE status = 'FAILED';

CREATE INDEX idx_gov_sync_log_target
    ON gov_sync_log(target_system);

CREATE INDEX idx_gov_sync_log_facility
    ON gov_sync_log(facility_id);

COMMENT ON TABLE gov_sync_log
    IS 'Outbox pattern table for government API calls. Every call is written here FIRST before execution. Background job processes PENDING rows. After 5 retries status becomes DEAD_LETTER and admin is alerted.';

COMMENT ON COLUMN gov_sync_log.idempotency_key
    IS 'Globally unique key in format {target}:{type}:{resource_id}:{timestamp}. Prevents duplicate submissions when retrying timed-out requests.';

COMMENT ON COLUMN gov_sync_log.next_retry_at
    IS 'Calculated as now() + (2^retry_count) minutes. Exponential backoff prevents overwhelming government APIs during outages.';


--  gov_reports

CREATE TABLE gov_reports (
                             id               UUID         NOT NULL DEFAULT gen_random_uuid(),

                             generated_by     UUID         NOT NULL,

                             geo_location_id  UUID         NOT NULL,

                             report_type      VARCHAR(32)  NOT NULL,

                             period           VARCHAR(16)  NOT NULL,

                             scope_level      VARCHAR(16)  NOT NULL,
                             aggregates       JSONB        NOT NULL,

                             hmis_push_status VARCHAR(16)  NOT NULL DEFAULT 'NOT_PUSHED',
                             generated_at     TIMESTAMP    NOT NULL DEFAULT now(),
                             pushed_at        TIMESTAMP,

                             CONSTRAINT pk_gov_reports
                                 PRIMARY KEY (id),

                             CONSTRAINT fk_gov_reports_generated_by
                                 FOREIGN KEY (generated_by)
                                     REFERENCES users(id),

                             CONSTRAINT fk_gov_reports_geo
                                 FOREIGN KEY (geo_location_id)
                                     REFERENCES geo_locations(id),

                             CONSTRAINT chk_gov_reports_type
                                 CHECK (report_type IN (
                                                        'VACCINATION_COVERAGE',
                                                        'ANC_ATTENDANCE',
                                                        'BIRTH_REGISTRATION',
                                                        'MATERNAL_HEALTH'
                                     )),

                             CONSTRAINT chk_gov_reports_scope
                                 CHECK (scope_level IN (
                                                        'NATIONAL',
                                                        'PROVINCE',
                                                        'DISTRICT',
                                                        'SECTOR'
                                     )),

                             CONSTRAINT chk_gov_reports_hmis_status
                                 CHECK (hmis_push_status IN (
                                                             'NOT_PUSHED',
                                                             'QUEUED',
                                                             'PUSHED',
                                                             'FAILED'
                                     ))
);

CREATE INDEX idx_gov_reports_type
    ON gov_reports(report_type);

CREATE INDEX idx_gov_reports_period
    ON gov_reports(period);

CREATE INDEX idx_gov_reports_hmis_status
    ON gov_reports(hmis_push_status)
    WHERE hmis_push_status IN ('NOT_PUSHED', 'QUEUED', 'FAILED');

CREATE INDEX idx_gov_reports_geo
    ON gov_reports(geo_location_id);

CREATE UNIQUE INDEX uq_gov_reports_type_period_geo
    ON gov_reports(report_type, period, geo_location_id);

COMMENT ON TABLE gov_reports
    IS 'Aggregated health statistics for MoH HMIS. Contains NO individual patient records. All fields in aggregates JSONB are computed statistics only.';

COMMENT ON COLUMN gov_reports.aggregates
    IS 'Computed statistics as JSONB. Never contains individual patient identifiers. Example: {"total_vaccinated": 416, "coverage_rate": 87.5, "missed_count": 62}';

COMMENT ON COLUMN gov_reports.period
    IS 'Time period in format YYYY-QN (quarterly), YYYY-MM (monthly), or YYYY (annual). Example: 2026-Q1, 2026-04, 2026';